import { Button } from "@mui/material";
import { BigNumber, ethers } from "ethers";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useContract } from "../hooks/contract";

const Home: NextPage = () => {
  const [address, setAddress] = useState("");
  const [balance, setBalance] = useState(BigNumber.from(0));
  const [erc20Balance, setERC20Balance] = useState(BigNumber.from(0));
  const { brokerContract, erc20Contract, signer } = useContract();

  useEffect(() => {
    if (!signer) return;
    signer.getBalance().then(setBalance);
    signer.getAddress().then(setAddress);
  }, [signer]);

  useEffect(() => {
    if (!erc20Contract || !address) return;
    erc20Contract.balanceOf(address).then(setERC20Balance);
  }, [erc20Contract, address]);

  return (
    <>
      <Head>
        <title>CWM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{`Balance: ${ethers.utils.formatEther(balance)}`}</div>
      <div>{`USDC: ${ethers.utils.formatEther(erc20Balance)}`}</div>
    </>
  );
};

export default Home;
