import { useContract } from "../hooks/contract";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { brokerContract, erc20Contract, signer } = useContract();
  return (
    <>
      <Head>
        <title>CWM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
